### ISSUE TITLE
.cms-overflow class on html makes whole page unscrollable after window resize

### ISSUE THREAD

**Issue by benzkji** [django-cms/django-cms#6566]
### Summary

When logged in and not in editing mode, if a make the browser window smaller than 1024px, my html tag gets the `cms-overflow` class, which results in a page that can no more be scrolled at all. A fresh reload solves the problem. To reproduce, make the viewport bigger than 1024px, and smaller again.

### Expected behaviour

The cms leaving scrolling as is.

### More infos

Downgrade to 3.5.2 solves the problem.

### Environment

* Python version: 2.7.14
* Django version: 1.11.latest
* django CMS version: 3.5.3

**Comment by wesleyboar** [comment]
**For users:**

This oddness still exists on 3.6.0; not sure about 3.7.0.

To resolve it, switch between "Edit" and "View published", using the CMS toolbar.

**For maintainers of the project:**

Why is this built into the app?

My own research reveals, for the latest version (as of this message) of the app:

- [a `CMS.settings.mode === 'structure'`](https://github.com/divio/django-cms/blob/8964d77b876ddb9221a12c64d1c4f5b5575b2049/cms/static/cms/js/modules/cms.structureboard.js#L713)
- [a button in the CMS toolbar](http://docs.django-cms.org/en/latest/user/reference/page_admin.html#the-structure-content-button)
- [no comment in the CSS](https://github.com/divio/django-cms/blob/8964d77b876ddb9221a12c64d1c4f5b5575b2049/cms/static/cms/sass/components/_structureboard.scss) ¹

¹ By the way, any use of `!important` in CSS should be commented to explain why such a heavy hand is used.

**Comment by benzkji** [comment]
this may have been resolved, as I remember recent activity in slack...a message from core devs would help?

**Comment by marksweb** [comment]
I've not come across this issue so I think you're right @benzkji & I'll close.

**Comment by aractru** [comment]
Still exists for django CMS 4.1.0 when browser window reaches a width 1020px.  But reproducing is super specific.  
1. Logged in as a CMS editor/admin
2. Go to the page, but particularly the URL override
3. Shrink window size down to 1020 px
4. Note that the URL in the browser also updates without reloading the page.  First it changes to "admin/cms/placeholder/object/11/edit/6/" then "admin/cms/placeholder/object/11/structure/6/".  When the URL changes to 'structure', that when...

Expected: 
Ability to scroll down

Actual:
No Ability to scroll.  The base html (<html>) element has the class "cms-overflow" which has the following property: `overflow: hidden !important;`

Seems like the issue is not a big deal, but was super concerning before I realized I couldn't reproduce it while logged in.  Recommending investigation as this could lead to more problems if there is bad code floating around in the source.  Sorry that I'm not a contributor.

**Comment by fsbraun** [comment]
Any connection with #7906 ?

**Comment by benzkji** [comment]
yep, long time classic :)
