### ISSUE TITLE
[BUG] Missing translations on 3.11.5

### ISSUE THREAD

**Issue by adrien-delhorme** [django-cms/django-cms#7840]
## Description

Some translations files (.po) are not compiled in this release (eg. French).
The CMS UI fallbacks to English.

## Steps to reproduce

1. Install django-cms 3.11.5
2. Log in to the CMS and change language to French
3. See that the CMS UI is in English 😀

## Expected behaviour

the CMS UI is in French

## Actual behaviour

the CMS UI is in English

## Additional information (CMS/Python/Django versions)

Python 3.11
Django 4.2.11
Django CMS 3.11.5

## Do you want to help fix this issue?

* [ ] Yes, I want to help fix this issue and I will join #workgroup-pr-review on [Slack](https://www.django-cms.org/slack) to confirm with the community that a PR is welcome. 
* [x] No, I only want to report the issue.

**Comment by fsbraun** [comment]
@adrien-delhorme Thanks for reporting this. It seems that the compiled French translations are missing (for whatever reason 😳). Should be fixed by running `. /manage.py compilemessages`.

**Comment by vinitkumar** [comment]
@adrien-delhorme Would you like to try the fix as suggested by @fsbraun and help fix this issue? Please let us know?

**Comment by adrien-delhorme** [comment]
The workaround is correct.
But I don't think I can help solve this issue: perhaps there was a problem during the publishing process?

**Comment by fsbraun** [comment]
@adrien-delhorme Is this fixed in current versions (Django CMS 3.11.9)?

**Comment by hamadr** [comment]
Hello everyone,
It seems the problem still exists in `django-cms` `3.11.9`.
Here is the output when I launch `compilemessages` on my project 
```
File “/python-env/lib/python3.7/site-packages/cms/locale/tr/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/tr/LC_MESSAGES/djangojs.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/pt/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/pt/LC_MESSAGES/djangojs.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/es/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/es/LC_MESSAGES/djangojs.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/sq/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/sq/LC_MESSAGES/djangojs.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/lt/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/lt/LC_MESSAGES/djangojs.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/ru/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/ru/LC_MESSAGES/djangojs.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/nl/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/nl/LC_MESSAGES/djangojs.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/ko_KR/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/ko_KR/LC_MESSAGES/djangojs.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/cs/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/cs/LC_MESSAGES/djangojs.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/ca/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/ca/LC_MESSAGES/djangojs.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/sv/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/sv/LC_MESSAGES/djangojs.po” is already compiled and up to date.
processing file django.po in /python-env/lib/python3.7/site-packages/cms/locale/ja/LC_MESSAGES
File “/python-env/lib/python3.7/site-packages/cms/locale/ja/LC_MESSAGES/djangojs.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/da/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/da/LC_MESSAGES/djangojs.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/zh_CN/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/zh_CN/LC_MESSAGES/djangojs.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/en/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/en/LC_MESSAGES/djangojs.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/nb/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/nb/LC_MESSAGES/djangojs.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/fa/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/fa/LC_MESSAGES/djangojs.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/fi/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/fi/LC_MESSAGES/djangojs.po” is already compiled and up to date.
processing file django.po in /python-env/lib/python3.7/site-packages/cms/locale/fr/LC_MESSAGES
processing file djangojs.po in /python-env/lib/python3.7/site-packages/cms/locale/fr/LC_MESSAGES
File “/python-env/lib/python3.7/site-packages/cms/locale/pt_BR/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/pt_BR/LC_MESSAGES/djangojs.po” is already compiled and up to date.
processing file django.po in /python-env/lib/python3.7/site-packages/cms/locale/pl/LC_MESSAGES
File “/python-env/lib/python3.7/site-packages/cms/locale/pl/LC_MESSAGES/djangojs.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/de/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/de/LC_MESSAGES/djangojs.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/ta/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/ta/LC_MESSAGES/djangojs.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/it/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/it/LC_MESSAGES/djangojs.po” is already compiled and up to date.
processing file django.po in /python-env/lib/python3.7/site-packages/cms/locale/zh_TW/LC_MESSAGES
File “/python-env/lib/python3.7/site-packages/cms/locale/zh_TW/LC_MESSAGES/djangojs.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/hr/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/hr/LC_MESSAGES/djangojs.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/uk/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/uk/LC_MESSAGES/djangojs.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/ar/LC_MESSAGES/django.po” is already compiled and up to date.
File “/python-env/lib/python3.7/site-packages/cms/locale/ar/LC_MESSAGES/djangojs.po” is already compiled and up to date.
```

You can see that there are some languages without an up to date po file
```
processing file django.po in /python-env/lib/python3.7/site-packages/cms/locale/ja/LC_MESSAGES
processing file django.po in /python-env/lib/python3.7/site-packages/cms/locale/fr/LC_MESSAGES
processing file djangojs.po in /python-env/lib/python3.7/site-packages/cms/locale/fr/LC_MESSAGES
processing file django.po in /python-env/lib/python3.7/site-packages/cms/locale/pl/LC_MESSAGES
processing file django.po in /python-env/lib/python3.7/site-packages/cms/locale/zh_TW/LC_MESSAGES
```

Would be glad to help if I can do something on my side.

Cheers
